/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as IndexRouteImport } from './routes/index'

const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ads.txt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ads.txt'
  id: '__root__' | '/' | '/ads.txt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsDottxtRoute: AdsDottxtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
