/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PestControlRouteImport } from './routes/pest-control'
import { Route as MarketPricesRouteImport } from './routes/market-prices'
import { Route as GovernmentSchemesRouteImport } from './routes/government-schemes'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CropDiseasesRouteImport } from './routes/crop-diseases'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as KnowledgeCenterSlugRouteImport } from './routes/knowledge-center.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PestControlRoute = PestControlRouteImport.update({
  id: '/pest-control',
  path: '/pest-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPricesRoute = MarketPricesRouteImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentSchemesRoute = GovernmentSchemesRouteImport.update({
  id: '/government-schemes',
  path: '/government-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDiseasesRoute = CropDiseasesRouteImport.update({
  id: '/crop-diseases',
  path: '/crop-diseases',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCenterSlugRoute = KnowledgeCenterSlugRouteImport.update({
  id: '/knowledge-center/$slug',
  path: '/knowledge-center/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/crop-diseases': typeof CropDiseasesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/government-schemes': typeof GovernmentSchemesRoute
  '/market-prices': typeof MarketPricesRoute
  '/pest-control': typeof PestControlRoute
  '/privacy': typeof PrivacyRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/knowledge-center/$slug': typeof KnowledgeCenterSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/crop-diseases': typeof CropDiseasesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/government-schemes': typeof GovernmentSchemesRoute
  '/market-prices': typeof MarketPricesRoute
  '/pest-control': typeof PestControlRoute
  '/privacy': typeof PrivacyRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/knowledge-center/$slug': typeof KnowledgeCenterSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/crop-diseases': typeof CropDiseasesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/government-schemes': typeof GovernmentSchemesRoute
  '/market-prices': typeof MarketPricesRoute
  '/pest-control': typeof PestControlRoute
  '/privacy': typeof PrivacyRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/knowledge-center/$slug': typeof KnowledgeCenterSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ads.txt'
    | '/auth'
    | '/contact'
    | '/crop-diseases'
    | '/disclaimer'
    | '/government-schemes'
    | '/market-prices'
    | '/pest-control'
    | '/privacy'
    | '/scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/knowledge-center/$slug'
    | '/news/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ads.txt'
    | '/auth'
    | '/contact'
    | '/crop-diseases'
    | '/disclaimer'
    | '/government-schemes'
    | '/market-prices'
    | '/pest-control'
    | '/privacy'
    | '/scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/knowledge-center/$slug'
    | '/news/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ads.txt'
    | '/auth'
    | '/contact'
    | '/crop-diseases'
    | '/disclaimer'
    | '/government-schemes'
    | '/market-prices'
    | '/pest-control'
    | '/privacy'
    | '/scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/knowledge-center/$slug'
    | '/news/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CropDiseasesRoute: typeof CropDiseasesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GovernmentSchemesRoute: typeof GovernmentSchemesRoute
  MarketPricesRoute: typeof MarketPricesRoute
  PestControlRoute: typeof PestControlRoute
  PrivacyRoute: typeof PrivacyRoute
  ScannerRoute: typeof ScannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  KnowledgeCenterSlugRoute: typeof KnowledgeCenterSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-control': {
      id: '/pest-control'
      path: '/pest-control'
      fullPath: '/pest-control'
      preLoaderRoute: typeof PestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-prices': {
      id: '/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof MarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-schemes': {
      id: '/government-schemes'
      path: '/government-schemes'
      fullPath: '/government-schemes'
      preLoaderRoute: typeof GovernmentSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-diseases': {
      id: '/crop-diseases'
      path: '/crop-diseases'
      fullPath: '/crop-diseases'
      preLoaderRoute: typeof CropDiseasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-center/$slug': {
      id: '/knowledge-center/$slug'
      path: '/knowledge-center/$slug'
      fullPath: '/knowledge-center/$slug'
      preLoaderRoute: typeof KnowledgeCenterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CropDiseasesRoute: CropDiseasesRoute,
  DisclaimerRoute: DisclaimerRoute,
  GovernmentSchemesRoute: GovernmentSchemesRoute,
  MarketPricesRoute: MarketPricesRoute,
  PestControlRoute: PestControlRoute,
  PrivacyRoute: PrivacyRoute,
  ScannerRoute: ScannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  KnowledgeCenterSlugRoute: KnowledgeCenterSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
